name: kiosk
description: "Kiosk application for DEPA generative AI hackathon"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  awesome_notifications: 0.9.3+1
  aws_common: 0.7.3
  aws_signature_v4: 0.6.3
  bloc: 8.1.4
  easy_localization_loader: 2.0.2
  equatable: 2.0.5
  flutter_bloc: 8.1.6
  flutter_chat_ui: 1.6.15
  flutter_dotenv: 5.0.2
  flutter_secure_storage: 4.2.1
  flutter_svg: 2.0.10
  get_it: 7.2.0
  go_router: 12.1.3
  http: 1.2.2
  intl: 0.19.0
  lottie: 3.1.2
  shared_preferences: 2.3.2
  sprintf: 6.0.0
  uuid: 4.5.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
