name: kiosk
description: "Kiosk application for DEPA generative AI hackathon"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  awesome_notifications: 0.9.3+1
  aws_common: 0.7.3
  aws_signature_v4: 0.6.3
  bloc: 8.1.4
  easy_localization_loader: 2.0.2
  equatable: 2.0.5
  flutter_bloc: 8.1.6
  flutter_chat_ui: 1.6.15
  flutter_dotenv: 5.0.2
  flutter_secure_storage: 4.2.1
  flutter_svg: 2.0.10
  get_it: 7.2.0
  go_router: 12.1.3
  http: 1.2.2
  intl: 0.19.0
  lottie: 3.1.2
  shared_preferences: 2.3.2
  sprintf: 6.0.0
  uuid: 4.5.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - translations/
    - .env-dev
  fonts:
    - family: THSarabunPSK
      fonts:
        - asset: assets/fonts/THSarabun.ttf
          weight: 400
        - asset: assets/fonts/THSarabun_Bold.ttf
          weight: 500
        - asset: assets/fonts/THSarabun_Bold_Italic.ttf
          weight: 700