import 'dart:ui';

const appBarColor = Color(0xFFB8232F);
const appbarTextColor = Color(0xFFFFFFFF);
const appbarArrowColor = Color(0xFFFFFFFF);
const pageLayoutBackgroundColor = Color(0xFFDEDEDE);
const bottomBarBackgroundColor = Color(0xFFF6F6F6);
const inputTextFillColor = Color(0xFFFFFFFF);
const chatPanelStartTimeColor = Color(0xFFFFFFFF);
const closeMinimizeIconColor = Color(0xFF000000);
const bubbleTextMessageColor = Color(0xFF000000);
const bubbleMessageColor = Color(0xFFFFFFFF);
const timerColor = Color(0xFF000000);
const quickTextBorderColor = Color(0xFF107EF4);
const quickTextMessageColor = Color(0xFF107EF4);
const quickTextColor = Color(0xFFFFFFFF);
const carouselBarColor = Color(0xFFFFFFFF);
const keptCarouselBarColor = Color(0xFFF6DEDE);
const growCarouselBarColor = Color(0xFFA4DDBE);
const funCarouselBarColor = Color(0xFF7AC3FF);
const togetherCarouselBarColor = Color(0xFFFFE5AC);
const carouselTitleMessageColor = Color(0xFFA81018);
const carouselDetailMessageColor = Color(0xFF000000);
const carouselButtonColor = Color(0xFFF0FBFD);
const carouselTextButtonColor = Color(0xFF108AF4);
const botEndedSessionTextColor = Color(0xFF000000);
const agentNameJoinedChatTextColor = Color(0xFF000000);
const dividerMessageColor = Color(0xFF000000);